spring.application.name=pensionat-kademina-customer-service

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_JDBC_URL:jdbc:mysql://customer-db:3306/customer_db}
spring.datasource.username=${MYSQLUSER:springUser}
spring.datasource.password=${MYSQLPASSWORD:secretPassword}

