name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup java environment
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests
        run: mvn test

      - name: Package
        run: mvn -B package -DskipTests

      - name: Login to Dockerhub
        if: github.event_name == 'push'
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: build image
        if: github.event_name == 'push'
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/customer-service:${{github.run_number}} .

      - name: push to docker hub
        if: github.event_name == 'push'
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/customer-service:${{github.run_number}}