name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: gabbe123
          MYSQL_DATABASE: customer_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup java environment
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: Build with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Login to Dockerhub
        if: github.event_name == 'push'
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: build image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/customer-service:${{github.run_number}} .

      - name: push to docker hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/customer-service:${{github.run_number}}

        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/customer_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: gabbe123
#test